name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build EXE
        run: pkg . --targets node18-win-x64 --output P2PCalc.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: P2PCalc-Windows
          path: P2PCalc.exe
